// Formula categories with Russian translations
// Based on 410 Excel-compatible functions in IronCalc

export interface FormulaInfo {
    name: string;        // English name for insertion
    localName: string;   // Russian name for display
    description: string; // Russian description
    syntax: string;      // Formula syntax example
}

export interface FormulaCategory {
    id: string;
    icon: string;
    name: string;
    formulas: FormulaInfo[];
}

export const formulaCategories: FormulaCategory[] = [
    {
        id: "math",
        icon: "🔢",
        name: "Математические",
        formulas: [
            { name: "SUM", localName: "СУММ", description: "Суммирует числа", syntax: "СУММ(число1; [число2]; ...)" },
            { name: "SUMIF", localName: "СУММЕСЛИ", description: "Сумма по условию", syntax: "СУММЕСЛИ(диапазон; критерий; [сумм_диапазон])" },
            { name: "SUMIFS", localName: "СУММЕСЛИМН", description: "Сумма по нескольким условиям", syntax: "СУММЕСЛИМН(сумм_диапазон; диапазон1; критерий1; ...)" },
            { name: "ABS", localName: "ABS", description: "Модуль числа", syntax: "ABS(число)" },
            { name: "ROUND", localName: "ОКРУГЛ", description: "Округляет число", syntax: "ОКРУГЛ(число; кол_разрядов)" },
            { name: "ROUNDUP", localName: "ОКРУГЛВВЕРХ", description: "Округляет вверх", syntax: "ОКРУГЛВВЕРХ(число; кол_разрядов)" },
            { name: "ROUNDDOWN", localName: "ОКРУГЛВНИЗ", description: "Округляет вниз", syntax: "ОКРУГЛВНИЗ(число; кол_разрядов)" },
            { name: "SQRT", localName: "КОРЕНЬ", description: "Квадратный корень", syntax: "КОРЕНЬ(число)" },
            { name: "POWER", localName: "СТЕПЕНЬ", description: "Возводит в степень", syntax: "СТЕПЕНЬ(число; степень)" },
            { name: "PI", localName: "ПИ", description: "Число π", syntax: "ПИ()" },
            { name: "MOD", localName: "ОСТАТ", description: "Остаток от деления", syntax: "ОСТАТ(число; делитель)" },
            { name: "PRODUCT", localName: "ПРОИЗВЕД", description: "Произведение чисел", syntax: "ПРОИЗВЕД(число1; [число2]; ...)" },
            { name: "QUOTIENT", localName: "ЧАСТНОЕ", description: "Целая часть деления", syntax: "ЧАСТНОЕ(делимое; делитель)" },
            { name: "RAND", localName: "СЛЧИС", description: "Случайное число", syntax: "СЛЧИС()" },
            { name: "RANDBETWEEN", localName: "СЛУЧМЕЖДУ", description: "Случайное в диапазоне", syntax: "СЛУЧМЕЖДУ(мин; макс)" },
            { name: "LN", localName: "LN", description: "Натуральный логарифм", syntax: "LN(число)" },
            { name: "LOG", localName: "LOG", description: "Логарифм", syntax: "LOG(число; [основание])" },
            { name: "LOG10", localName: "LOG10", description: "Десятичный логарифм", syntax: "LOG10(число)" },
            { name: "EXP", localName: "EXP", description: "Экспонента", syntax: "EXP(число)" },
            { name: "FACT", localName: "ФАКТР", description: "Факториал", syntax: "ФАКТР(число)" },
        ],
    },
    {
        id: "trig",
        icon: "📐",
        name: "Тригонометрические",
        formulas: [
            { name: "SIN", localName: "SIN", description: "Синус угла", syntax: "SIN(число)" },
            { name: "COS", localName: "COS", description: "Косинус угла", syntax: "COS(число)" },
            { name: "TAN", localName: "TAN", description: "Тангенс угла", syntax: "TAN(число)" },
            { name: "ASIN", localName: "ASIN", description: "Арксинус", syntax: "ASIN(число)" },
            { name: "ACOS", localName: "ACOS", description: "Арккосинус", syntax: "ACOS(число)" },
            { name: "ATAN", localName: "ATAN", description: "Арктангенс", syntax: "ATAN(число)" },
            { name: "ATAN2", localName: "ATAN2", description: "Арктангенс от X и Y", syntax: "ATAN2(x; y)" },
            { name: "SINH", localName: "SINH", description: "Гиперболический синус", syntax: "SINH(число)" },
            { name: "COSH", localName: "COSH", description: "Гиперболический косинус", syntax: "COSH(число)" },
            { name: "TANH", localName: "TANH", description: "Гиперболический тангенс", syntax: "TANH(число)" },
            { name: "RADIANS", localName: "РАДИАНЫ", description: "Градусы в радианы", syntax: "РАДИАНЫ(градусы)" },
            { name: "DEGREES", localName: "ГРАДУСЫ", description: "Радианы в градусы", syntax: "ГРАДУСЫ(радианы)" },
        ],
    },
    {
        id: "statistical",
        icon: "📊",
        name: "Статистические",
        formulas: [
            { name: "AVERAGE", localName: "СРЗНАЧ", description: "Среднее арифметическое", syntax: "СРЗНАЧ(число1; [число2]; ...)" },
            { name: "AVERAGEIF", localName: "СРЗНАЧЕСЛИ", description: "Среднее по условию", syntax: "СРЗНАЧЕСЛИ(диапазон; критерий; [сред_диапазон])" },
            { name: "AVERAGEIFS", localName: "СРЗНАЧЕСЛИМН", description: "Среднее по нескольким условиям", syntax: "СРЗНАЧЕСЛИМН(сред_диапазон; диапазон1; критерий1; ...)" },
            { name: "COUNT", localName: "СЧЁТ", description: "Количество чисел", syntax: "СЧЁТ(значение1; [значение2]; ...)" },
            { name: "COUNTA", localName: "СЧЁТЗ", description: "Количество непустых", syntax: "СЧЁТЗ(значение1; [значение2]; ...)" },
            { name: "COUNTBLANK", localName: "СЧИТАТЬПУСТОТЫ", description: "Количество пустых", syntax: "СЧИТАТЬПУСТОТЫ(диапазон)" },
            { name: "COUNTIF", localName: "СЧЁТЕСЛИ", description: "Счёт по условию", syntax: "СЧЁТЕСЛИ(диапазон; критерий)" },
            { name: "COUNTIFS", localName: "СЧЁТЕСЛИМН", description: "Счёт по нескольким условиям", syntax: "СЧЁТЕСЛИМН(диапазон1; критерий1; ...)" },
            { name: "MAX", localName: "МАКС", description: "Максимум", syntax: "МАКС(число1; [число2]; ...)" },
            { name: "MAXIFS", localName: "МАКСЕСЛИ", description: "Максимум по условиям", syntax: "МАКСЕСЛИ(макс_диапазон; диапазон1; критерий1; ...)" },
            { name: "MIN", localName: "МИН", description: "Минимум", syntax: "МИН(число1; [число2]; ...)" },
            { name: "MINIFS", localName: "МИНЕСЛИ", description: "Минимум по условиям", syntax: "МИНЕСЛИ(мин_диапазон; диапазон1; критерий1; ...)" },
            { name: "MEDIAN", localName: "МЕДИАНА", description: "Медиана", syntax: "МЕДИАНА(число1; [число2]; ...)" },
            { name: "LARGE", localName: "НАИБОЛЬШИЙ", description: "K-ое наибольшее", syntax: "НАИБОЛЬШИЙ(массив; k)" },
            { name: "SMALL", localName: "НАИМЕНЬШИЙ", description: "K-ое наименьшее", syntax: "НАИМЕНЬШИЙ(массив; k)" },
            { name: "STDEV.S", localName: "СТАНДОТКЛОН.В", description: "Стандартное отклонение (выборка)", syntax: "СТАНДОТКЛОН.В(число1; [число2]; ...)" },
            { name: "STDEV.P", localName: "СТАНДОТКЛОН.Г", description: "Стандартное отклонение (ген.совокупность)", syntax: "СТАНДОТКЛОН.Г(число1; [число2]; ...)" },
            { name: "VAR.S", localName: "ДИСП.В", description: "Дисперсия (выборка)", syntax: "ДИСП.В(число1; [число2]; ...)" },
            { name: "VAR.P", localName: "ДИСП.Г", description: "Дисперсия (ген.совокупность)", syntax: "ДИСП.Г(число1; [число2]; ...)" },
        ],
    },
    {
        id: "text",
        icon: "📝",
        name: "Текстовые",
        formulas: [
            { name: "CONCATENATE", localName: "СЦЕПИТЬ", description: "Объединяет текст", syntax: "СЦЕПИТЬ(текст1; [текст2]; ...)" },
            { name: "CONCAT", localName: "ОБЪЕДИНИТЬ", description: "Объединяет диапазоны", syntax: "ОБЪЕДИНИТЬ(текст1; [текст2]; ...)" },
            { name: "TEXTJOIN", localName: "ОБЪЕДИНИТЬТЕКСТ", description: "Объединяет с разделителем", syntax: "ОБЪЕДИНИТЬТЕКСТ(разделитель; игнор_пустые; текст1; ...)" },
            { name: "LEFT", localName: "ЛЕВСИМВ", description: "Левые символы", syntax: "ЛЕВСИМВ(текст; [кол_символов])" },
            { name: "RIGHT", localName: "ПРАВСИМВ", description: "Правые символы", syntax: "ПРАВСИМВ(текст; [кол_символов])" },
            { name: "MID", localName: "ПСТР", description: "Символы из середины", syntax: "ПСТР(текст; начало; кол_символов)" },
            { name: "LEN", localName: "ДЛСТР", description: "Длина текста", syntax: "ДЛСТР(текст)" },
            { name: "FIND", localName: "НАЙТИ", description: "Позиция подстроки", syntax: "НАЙТИ(искомый_текст; текст; [нач_позиция])" },
            { name: "SEARCH", localName: "ПОИСК", description: "Поиск (без регистра)", syntax: "ПОИСК(искомый_текст; текст; [нач_позиция])" },
            { name: "REPLACE", localName: "ЗАМЕНИТЬ", description: "Замена по позиции", syntax: "ЗАМЕНИТЬ(старый_текст; начало; кол; новый_текст)" },
            { name: "SUBSTITUTE", localName: "ПОДСТАВИТЬ", description: "Замена текста", syntax: "ПОДСТАВИТЬ(текст; старый; новый; [номер])" },
            { name: "UPPER", localName: "ПРОПИСН", description: "В верхний регистр", syntax: "ПРОПИСН(текст)" },
            { name: "LOWER", localName: "СТРОЧН", description: "В нижний регистр", syntax: "СТРОЧН(текст)" },
            { name: "PROPER", localName: "ПРОПНАЧ", description: "Каждое слово с заглавной", syntax: "ПРОПНАЧ(текст)" },
            { name: "TRIM", localName: "СЖПРОБЕЛЫ", description: "Удаляет лишние пробелы", syntax: "СЖПРОБЕЛЫ(текст)" },
            { name: "TEXT", localName: "ТЕКСТ", description: "Форматирует как текст", syntax: "ТЕКСТ(значение; формат)" },
            { name: "VALUE", localName: "ЗНАЧЕН", description: "Текст в число", syntax: "ЗНАЧЕН(текст)" },
            { name: "REPT", localName: "ПОВТОР", description: "Повторяет текст", syntax: "ПОВТОР(текст; кол_раз)" },
            { name: "CHAR", localName: "СИМВОЛ", description: "Символ по коду", syntax: "СИМВОЛ(код)" },
            { name: "CODE", localName: "КОДСИМВ", description: "Код символа", syntax: "КОДСИМВ(текст)" },
        ],
    },
    {
        id: "datetime",
        icon: "📅",
        name: "Дата и время",
        formulas: [
            { name: "TODAY", localName: "СЕГОДНЯ", description: "Текущая дата", syntax: "СЕГОДНЯ()" },
            { name: "NOW", localName: "ТДАТА", description: "Текущие дата и время", syntax: "ТДАТА()" },
            { name: "DATE", localName: "ДАТА", description: "Создаёт дату", syntax: "ДАТА(год; месяц; день)" },
            { name: "TIME", localName: "ВРЕМЯ", description: "Создаёт время", syntax: "ВРЕМЯ(час; минута; секунда)" },
            { name: "YEAR", localName: "ГОД", description: "Год из даты", syntax: "ГОД(дата)" },
            { name: "MONTH", localName: "МЕСЯЦ", description: "Месяц из даты", syntax: "МЕСЯЦ(дата)" },
            { name: "DAY", localName: "ДЕНЬ", description: "День из даты", syntax: "ДЕНЬ(дата)" },
            { name: "HOUR", localName: "ЧАС", description: "Час из времени", syntax: "ЧАС(время)" },
            { name: "MINUTE", localName: "МИНУТЫ", description: "Минуты из времени", syntax: "МИНУТЫ(время)" },
            { name: "SECOND", localName: "СЕКУНДЫ", description: "Секунды из времени", syntax: "СЕКУНДЫ(время)" },
            { name: "WEEKDAY", localName: "ДЕНЬНЕД", description: "День недели", syntax: "ДЕНЬНЕД(дата; [тип])" },
            { name: "WEEKNUM", localName: "НОМНЕДЕЛИ", description: "Номер недели", syntax: "НОМНЕДЕЛИ(дата; [тип])" },
            { name: "DAYS", localName: "ДНИ", description: "Дней между датами", syntax: "ДНИ(конец; начало)" },
            { name: "DATEDIF", localName: "РАЗНДАТ", description: "Разница дат", syntax: "РАЗНДАТ(начало; конец; единица)" },
            { name: "EDATE", localName: "ДАТАМЕС", description: "Дата + месяцы", syntax: "ДАТАМЕС(дата; месяцы)" },
            { name: "EOMONTH", localName: "КОНМЕСЯЦА", description: "Конец месяца", syntax: "КОНМЕСЯЦА(дата; месяцы)" },
            { name: "NETWORKDAYS", localName: "ЧИСТРАБДНИ", description: "Рабочие дни", syntax: "ЧИСТРАБДНИ(начало; конец; [праздники])" },
            { name: "WORKDAY", localName: "РАБДЕНЬ", description: "Рабочий день", syntax: "РАБДЕНЬ(дата; дни; [праздники])" },
        ],
    },
    {
        id: "financial",
        icon: "💰",
        name: "Финансовые",
        formulas: [
            { name: "PMT", localName: "ПЛТ", description: "Платёж по кредиту", syntax: "ПЛТ(ставка; кол_пер; нс; [бс]; [тип])" },
            { name: "PV", localName: "ПС", description: "Приведённая стоимость", syntax: "ПС(ставка; кол_пер; плт; [бс]; [тип])" },
            { name: "FV", localName: "БС", description: "Будущая стоимость", syntax: "БС(ставка; кол_пер; плт; [пс]; [тип])" },
            { name: "NPV", localName: "НПЗ", description: "Чистая приведённая стоимость", syntax: "НПЗ(ставка; значение1; [значение2]; ...)" },
            { name: "IRR", localName: "ВСД", description: "Внутренняя ставка доходности", syntax: "ВСД(значения; [предположение])" },
            { name: "RATE", localName: "СТАВКА", description: "Процентная ставка", syntax: "СТАВКА(кол_пер; плт; пс; [бс]; [тип]; [предп])" },
            { name: "NPER", localName: "КПЕР", description: "Количество периодов", syntax: "КПЕР(ставка; плт; пс; [бс]; [тип])" },
            { name: "IPMT", localName: "ПРПЛТ", description: "Процентный платёж", syntax: "ПРПЛТ(ставка; период; кол_пер; пс; [бс]; [тип])" },
            { name: "PPMT", localName: "ОСПЛТ", description: "Основной платёж", syntax: "ОСПЛТ(ставка; период; кол_пер; пс; [бс]; [тип])" },
            { name: "SLN", localName: "АПЛ", description: "Линейная амортизация", syntax: "АПЛ(нач_стоимость; ост_стоимость; срок)" },
            { name: "DB", localName: "ФУО", description: "Амортизация (фикс.)", syntax: "ФУО(нач_стоимость; ост_стоимость; срок; период; [месяцы])" },
            { name: "DDB", localName: "ДДОБ", description: "Двойная амортизация", syntax: "ДДОБ(нач_стоимость; ост_стоимость; срок; период; [коэф])" },
        ],
    },
    {
        id: "lookup",
        icon: "🔍",
        name: "Поиск и ссылки",
        formulas: [
            { name: "VLOOKUP", localName: "ВПР", description: "Вертикальный поиск", syntax: "ВПР(искомое; таблица; номер_столбца; [интервал])" },
            { name: "HLOOKUP", localName: "ГПР", description: "Горизонтальный поиск", syntax: "ГПР(искомое; таблица; номер_строки; [интервал])" },
            { name: "XLOOKUP", localName: "ПРОСМОТРX", description: "Расширенный поиск", syntax: "ПРОСМОТРX(искомое; диап_поиска; диап_возврата; [не_найдено]; [режим]; [направление])" },
            { name: "INDEX", localName: "ИНДЕКС", description: "Значение по индексу", syntax: "ИНДЕКС(массив; номер_строки; [номер_столбца])" },
            { name: "MATCH", localName: "ПОИСКПОЗ", description: "Позиция значения", syntax: "ПОИСКПОЗ(искомое; диапазон; [тип])" },
            { name: "XMATCH", localName: "ПОИСКПОЗX", description: "Расширенный ПОИСКПОЗ", syntax: "ПОИСКПОЗX(искомое; диапазон; [режим]; [направление])" },
            { name: "LOOKUP", localName: "ПРОСМОТР", description: "Поиск значения", syntax: "ПРОСМОТР(искомое; вектор_поиска; [вектор_результата])" },
            { name: "CHOOSE", localName: "ВЫБОР", description: "Выбор по номеру", syntax: "ВЫБОР(номер; значение1; [значение2]; ...)" },
            { name: "OFFSET", localName: "СМЕЩ", description: "Смещённая ссылка", syntax: "СМЕЩ(ссылка; строки; столбцы; [высота]; [ширина])" },
            { name: "INDIRECT", localName: "ДВССЫЛ", description: "Ссылка из текста", syntax: "ДВССЫЛ(ссылка_текст; [a1])" },
            { name: "ROW", localName: "СТРОКА", description: "Номер строки", syntax: "СТРОКА([ссылка])" },
            { name: "COLUMN", localName: "СТОЛБЕЦ", description: "Номер столбца", syntax: "СТОЛБЕЦ([ссылка])" },
            { name: "ROWS", localName: "ЧСТРОК", description: "Количество строк", syntax: "ЧСТРОК(массив)" },
            { name: "COLUMNS", localName: "ЧИСЛСТОЛБ", description: "Количество столбцов", syntax: "ЧИСЛСТОЛБ(массив)" },
        ],
    },
    {
        id: "logical",
        icon: "⚡",
        name: "Логические",
        formulas: [
            { name: "IF", localName: "ЕСЛИ", description: "Условие", syntax: "ЕСЛИ(условие; если_истина; [если_ложь])" },
            { name: "IFS", localName: "ЕСЛИМН", description: "Несколько условий", syntax: "ЕСЛИМН(условие1; значение1; [условие2; значение2]; ...)" },
            { name: "IFERROR", localName: "ЕСЛИОШИБКА", description: "Обработка ошибки", syntax: "ЕСЛИОШИБКА(значение; значение_если_ошибка)" },
            { name: "IFNA", localName: "ЕСНД", description: "Обработка #Н/Д", syntax: "ЕСНД(значение; значение_если_нд)" },
            { name: "AND", localName: "И", description: "Логическое И", syntax: "И(условие1; [условие2]; ...)" },
            { name: "OR", localName: "ИЛИ", description: "Логическое ИЛИ", syntax: "ИЛИ(условие1; [условие2]; ...)" },
            { name: "NOT", localName: "НЕ", description: "Логическое НЕ", syntax: "НЕ(условие)" },
            { name: "XOR", localName: "ИСКЛИЛИ", description: "Исключающее ИЛИ", syntax: "ИСКЛИЛИ(условие1; [условие2]; ...)" },
            { name: "TRUE", localName: "ИСТИНА", description: "Значение ИСТИНА", syntax: "ИСТИНА()" },
            { name: "FALSE", localName: "ЛОЖЬ", description: "Значение ЛОЖЬ", syntax: "ЛОЖЬ()" },
            { name: "SWITCH", localName: "ПЕРЕКЛЮЧ", description: "Выбор из вариантов", syntax: "ПЕРЕКЛЮЧ(выражение; значение1; результат1; ...)" },
        ],
    },
    {
        id: "info",
        icon: "ℹ️",
        name: "Информационные",
        formulas: [
            { name: "ISBLANK", localName: "ЕПУСТО", description: "Пустая ячейка?", syntax: "ЕПУСТО(значение)" },
            { name: "ISERROR", localName: "ЕОШИБКА", description: "Ошибка?", syntax: "ЕОШИБКА(значение)" },
            { name: "ISNA", localName: "ЕНД", description: "#Н/Д?", syntax: "ЕНД(значение)" },
            { name: "ISNUMBER", localName: "ЕЧИСЛО", description: "Число?", syntax: "ЕЧИСЛО(значение)" },
            { name: "ISTEXT", localName: "ЕТЕКСТ", description: "Текст?", syntax: "ЕТЕКСТ(значение)" },
            { name: "ISLOGICAL", localName: "ЕЛОГИЧ", description: "Логическое?", syntax: "ЕЛОГИЧ(значение)" },
            { name: "ISEVEN", localName: "ЕЧЁТН", description: "Чётное?", syntax: "ЕЧЁТН(число)" },
            { name: "ISODD", localName: "ЕНЕЧЁТ", description: "Нечётное?", syntax: "ЕНЕЧЁТ(число)" },
            { name: "TYPE", localName: "ТИП", description: "Тип значения", syntax: "ТИП(значение)" },
            { name: "N", localName: "Ч", description: "Преобразует в число", syntax: "Ч(значение)" },
            { name: "NA", localName: "НД", description: "Возвращает #Н/Д", syntax: "НД()" },
        ],
    },
    {
        id: "array",
        icon: "📐",
        name: "Динамические массивы",
        formulas: [
            { name: "FILTER", localName: "ФИЛЬТР", description: "Фильтрует массив", syntax: "ФИЛЬТР(массив; включить; [если_пусто])" },
            { name: "SORT", localName: "СОРТИРОВКА", description: "Сортирует массив", syntax: "СОРТИРОВКА(массив; [индекс]; [порядок]; [по_столбцу])" },
            { name: "SORTBY", localName: "СОРТПО", description: "Сортирует по другому массиву", syntax: "СОРТПО(массив; по_массиву1; [порядок1]; ...)" },
            { name: "UNIQUE", localName: "УНИКАЛЬНЫЕ", description: "Уникальные значения", syntax: "УНИКАЛЬНЫЕ(массив; [по_столбцу]; [один_раз])" },
            { name: "SEQUENCE", localName: "ПОСЛЕДОВ", description: "Последовательность чисел", syntax: "ПОСЛЕДОВ(строки; [столбцы]; [начало]; [шаг])" },
            { name: "RANDARRAY", localName: "СЛУЧМАССИВ", description: "Массив случайных чисел", syntax: "СЛУЧМАССИВ([строки]; [столбцы]; [мин]; [макс]; [целые])" },
            { name: "TAKE", localName: "ВЗЯТЬ", description: "Берёт элементы массива", syntax: "ВЗЯТЬ(массив; строки; [столбцы])" },
            { name: "DROP", localName: "ОТБРОСИТЬ", description: "Отбрасывает элементы", syntax: "ОТБРОСИТЬ(массив; строки; [столбцы])" },
            { name: "CHOOSECOLS", localName: "ВЫБСТОЛБ", description: "Выбирает столбцы", syntax: "ВЫБСТОЛБ(массив; столб1; [столб2]; ...)" },
            { name: "CHOOSEROWS", localName: "ВЫБСТРОК", description: "Выбирает строки", syntax: "ВЫБСТРОК(массив; строка1; [строка2]; ...)" },
            { name: "VSTACK", localName: "ВСТОЛБ", description: "Объединяет по вертикали", syntax: "ВСТОЛБ(массив1; [массив2]; ...)" },
            { name: "HSTACK", localName: "ВСТР", description: "Объединяет по горизонтали", syntax: "ВСТР(массив1; [массив2]; ...)" },
        ],
    },
];

export default formulaCategories;
